#!/bin/sh 
########################################################################
# mmmanager, Script for management the mmwireless
# Copyright (C) 2014  Manuel Moscoso Dominguez manuel.moscoso.d@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
########################################################################
# Manuel Moscoso Dominguez <manuel.moscoso.d@gmail.com>
########################################################################
### BEGIN INIT INFO
# Provides:          mmmanager
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: guias-a-db integration of two system.
# Description:       This script allow to users integration of
# 					guide information with mysql database.
### END INIT INFO
 
## # Change the next 3 lines to suit where you install your script and 
# what you want to call it
### Location of mmwireless
DIR=/home/mmoscoso/Documentos/workspace/mmwireless/src/mmwireless
DAEMON=$DIR
DAEMON_NAME=mmwireless
DAEMON_USER=root
CURRENT_USER=$USER

# Location for store (process ID)
PIDFILE=/var/run/$DAEMON_NAME.pid
. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

check_user () {
	if [ $DAEMON_USER != $CURRENT_USER ]
	then
		log_daemon_msg "This script must be run as root"
		exit 1
	fi
}

case "$1" in
    start|stop)
		check_user    
        do_${1}
        ;;
 
    restart|reload|force-reload)
        check_user
        do_stop
        do_start
        ;;
 
    status)
        check_user
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
		check_user
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0
